       IDENTIFICATION DIVISION.
       PROGRAM-ID. DBLOGIN.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01  WS-DB-USER      PIC X(8)  VALUE 'BATCH01'.
       01  WS-DB-PASSWORD  PIC X(12) VALUE SPACES.
       01  WS-RC           PIC S9(4) COMP.
       PROCEDURE DIVISION.
           ACCEPT WS-DB-PASSWORD FROM ENVIRONMENT 'DB_PASSWORD'.
           CALL 'DBLOGON' USING WS-DB-USER WS-DB-PASSWORD WS-RC.
           GOBACK.
