       IDENTIFICATION DIVISION.
       PROGRAM-ID. DBCMD.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-SCRIPT            PIC X(120).
       01 WS-CMD               PIC X(200).
       PROCEDURE DIVISION.
           EXEC SQL SELECT SCRIPT_NAME INTO :WS-SCRIPT
               FROM JOB_CONTROL WHERE ID = 1 END-EXEC
           STRING 'sh ' WS-SCRIPT DELIMITED BY SIZE INTO WS-CMD
           CALL 'SYSTEM' USING WS-CMD
           GOBACK.
