       IDENTIFICATION DIVISION.
       PROGRAM-ID. BILLDATE.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01  WS-DATE PIC X(8).
       PROCEDURE DIVISION.
           CALL 'DATECONV' USING WS-DATE
           DISPLAY WS-DATE
           GOBACK.
