       IDENTIFICATION DIVISION.
       PROGRAM-ID. ACCTVIEW.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 CA.
          05 CA-SELECTED PIC X(11).
       01 WS-KEY PIC X(11).
       01 ACCT-REC PIC X(300).
       LINKAGE SECTION.
       01 DFHCOMMAREA PIC X(11).
       PROCEDURE DIVISION.
           IF EIBCALEN = 0
               EXEC CICS RETURN END-EXEC
           END-IF.
           MOVE DFHCOMMAREA TO CA.
           MOVE CA-SELECTED TO WS-KEY.
           EXEC CICS READ FILE('ACCTDAT') INTO(ACCT-REC)
               RIDFLD(WS-KEY) UPDATE END-EXEC.
           EXEC CICS DELETE FILE('ACCTDAT') END-EXEC.
           EXEC CICS RETURN END-EXEC.
