// SPDX-License-Identifier: AGPL-3.0-or-later
// docs/reference/ is what diag/generate-reference.mjs writes from `cobolwork capabilities` now, the
// facts behind it cover the command line and the code, and the pages pass an accessibility check.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { capabilities, COMMANDS, GLOBAL_OPTIONS } from '../lib/capabilities.mjs';
import { ENVIRONMENT } from '../lib/reference-facts.mjs';
import { renderReference } from '../diag/generate-reference.mjs';
import './pin-machine.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const REFERENCE = join(ROOT, 'docs', 'reference');
const pages = renderReference();

// Problems with one Markdown page, as a list of sentences; empty when it passes.
function accessibilityProblems(name, text) {
  const problems = [];
  const lines = text.split('\n');
  let fenced = false;
  let level = 0;
  let h1 = 0;
  let table = null;
  lines.forEach((line, i) => {
    const at = `${name}:${i + 1}`;
    if (line.startsWith('```')) { fenced = !fenced; return; }
    if (fenced) return;
    const heading = /^(#{1,6}) \S/.exec(line);
    if (heading) {
      const n = heading[1].length;
      if (n > level + 1) problems.push(`${at} heading level jumps from ${level} to ${n}`);
      if (n === 1) h1++;
      level = n;
    }
    if (line.startsWith('|')) {
      if (table === null) table = { start: i, rows: 0 };
      table.rows++;
      if (table.rows === 2 && !/^\|(\s*:?-+:?\s*\|)+\s*$/.test(line)) problems.push(`${at} table has no header row`);
    } else {
      if (table && table.rows < 2) problems.push(`${name}:${table.start + 1} table has no header row`);
      table = null;
    }
    for (const m of line.matchAll(/(!?)\[([^\]]*)\]\(([^)]*)\)/g)) {
      if (m[1] && !m[2].trim()) problems.push(`${at} image without alt text`);
      if (!m[1] && /^(here|click|click here|link|this|more|read more)$/i.test(m[2].replace(/[`*_]/g, '').trim())) problems.push(`${at} link text "${m[2]}" says nothing`);
      if (!m[1] && !m[2].trim()) problems.push(`${at} link with no text`);
    }
    if (/<img\b(?![^>]*\balt=["'][^"']+["'])/i.test(line)) problems.push(`${at} image without alt text`);
  });
  if (table && table.rows < 2) problems.push(`${name}:${table.start + 1} table has no header row`);
  if (h1 !== 1) problems.push(`${name} has ${h1} h1 headings`);
  return problems;
}

test('the committed reference pages are what the generator writes now', () => {
  const committed = readdirSync(REFERENCE).filter((f) => f.endsWith('.md')).sort();
  assert.deepEqual(committed, [...pages.keys()].sort(), 'run node diag/generate-reference.mjs');
  for (const [name, text] of pages) {
    assert.equal(readFileSync(join(REFERENCE, name), 'utf8').replace(/\r\n/g, '\n'), text, `${name} is stale: run node diag/generate-reference.mjs`);
  }
});

test('every page says it is generated and by which command', () => {
  for (const [name, text] of pages) assert.match(text, /generated by `node diag\/generate-reference\.mjs` from `cobolwork capabilities`/, name);
});

test('no page carries a machine path or a carriage return', () => {
  for (const [name, text] of pages) {
    assert.ok(!text.includes('\r'), name);
    assert.ok(!/(^|[\s`(])(\/(Users|home|tmp)\/|[A-Za-z]:\\)/.test(text), name);
  }
});

test('the reference has a page for every command, and every link in it resolves', () => {
  for (const name of Object.keys(COMMANDS)) assert.ok(pages.has(`${name}.md`), name);
  for (const [name, text] of pages) {
    for (const m of text.matchAll(/\]\(([^)#]+)\)/g)) assert.ok(pages.has(m[1]), `${name} links to ${m[1]}`);
  }
});

test('the pages pass the accessibility check', () => {
  for (const [name, text] of pages) assert.deepEqual(accessibilityProblems(name, text), [], name);
});

test('the accessibility check catches what it is meant to', () => {
  assert.ok(accessibilityProblems('a.md', '# A\n\n### C\n').some((p) => /jumps/.test(p)));
  assert.ok(accessibilityProblems('a.md', '# A\n\n# B\n').some((p) => /2 h1/.test(p)));
  assert.ok(accessibilityProblems('a.md', '# A\n\n| x | y |\n').some((p) => /header row/.test(p)));
  assert.ok(accessibilityProblems('a.md', '# A\n\n| x | y |\n| a | b |\n').some((p) => /header row/.test(p)));
  assert.ok(accessibilityProblems('a.md', '# A\n\nsee [here](b.md)\n').some((p) => /says nothing/.test(p)));
  assert.ok(accessibilityProblems('a.md', '# A\n\n![](b.png)\n').some((p) => /alt text/.test(p)));
  assert.ok(accessibilityProblems('a.md', '# A\n\n<img src="b.png">\n').some((p) => /alt text/.test(p)));
  assert.deepEqual(accessibilityProblems('a.md', '# A\n\n## B\n\n| x | y |\n|---|---|\n| a | b |\n\nsee [the index](b.md)\n'), []);
});

test('capabilities documents every option, with the words the pages print', () => {
  const caps = capabilities();
  const named = new Set([...Object.values(COMMANDS).flatMap((c) => c.options), ...GLOBAL_OPTIONS]);
  assert.deepEqual(Object.keys(caps.options).sort(), [...named].sort());
  for (const [name, o] of Object.entries(caps.options)) assert.ok(o.summary, name);
  for (const [name, c] of Object.entries(caps.commands)) {
    assert.ok(c.summary, name);
    assert.ok(c.exit.length && c.exit.some((e) => e.status === 2), `${name} lists status 2`);
  }
});

test('capabilities lists every environment variable the code reads', () => {
  const internal = new Set(['DF_REPOS', 'DF_FLAT', 'DF_PROGRESS']);
  const files = [join(ROOT, 'bin', 'cobolwork.mjs')];
  const walk = (dir) => { for (const e of readdirSync(dir, { withFileTypes: true })) { const p = join(dir, e.name); if (e.isDirectory()) walk(p); else if (p.endsWith('.mjs')) files.push(p); } };
  walk(join(ROOT, 'lib'));
  const source = files.map((f) => readFileSync(f, 'utf8')).join('\n');
  const read = new Set([
    ...[...source.matchAll(/\bprocess\.env\.([A-Z][A-Z0-9_]+)|\benv\.((?:COBOLWORK_|COBCPY)[A-Z0-9_]*)/g)].map((m) => m[1] || m[2]),
    ...[...source.matchAll(/'((?:COBOLWORK_|COBCPY)[A-Z0-9_]*)'/g)].map((m) => m[1]),
  ]);
  for (const n of internal) read.delete(n);
  assert.deepEqual([...read].filter((n) => !ENVIRONMENT.some((e) => e.name === n)).sort(), [], 'every variable read is listed');
  assert.deepEqual(ENVIRONMENT.map((e) => e.name).filter((n) => !read.has(n)).sort(), [], 'every variable listed is read');
});

test('capabilities lists every key the site file reads', () => {
  const schema = JSON.parse(readFileSync(join(ROOT, 'schema', 'cobolwork.site.schema.json'), 'utf8'));
  assert.deepEqual(capabilities().siteFile.keys.map((k) => k.key), Object.keys(schema.properties));
  for (const k of capabilities().siteFile.keys) assert.ok(k.summary, k.key);
});

test('the reference exists on disk', () => {
  assert.ok(existsSync(join(REFERENCE, 'README.md')));
});
