       IDENTIFICATION DIVISION.
       PROGRAM-ID. N3.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-STMT          PIC X(80).
       01 WS-CMD           PIC X(80).
       PROCEDURE DIVISION.
           MOVE 'SELECT 1 FROM SYSIBM.SYSDUMMY1' TO WS-STMT
           EXEC SQL EXECUTE IMMEDIATE :WS-STMT END-EXEC
           MOVE 'ls -l' TO WS-CMD
           CALL 'SYSTEM' USING WS-CMD
           GOBACK.
