       IDENTIFICATION DIVISION.
       PROGRAM-ID. CCALLEE.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-LEN           PIC S9(4) COMP.
       LINKAGE SECTION.
       01 DFHCOMMAREA      PIC X(50).
       PROCEDURE DIVISION.
           IF EIBCALEN > 0
               MOVE EIBCALEN TO WS-LEN
           END-IF
           EXEC CICS RETURN END-EXEC.
