       IDENTIFICATION DIVISION.
       PROGRAM-ID. S1.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-Q             PIC X(200).
       01 WS-STMT          PIC X(400).
       PROCEDURE DIVISION.
           EXEC CICS WEB RECEIVE INTO(WS-Q) LENGTH(200) END-EXEC
           STRING 'SELECT * FROM T WHERE C = ' WS-Q DELIMITED BY SIZE
               INTO WS-STMT
           EXEC SQL EXECUTE IMMEDIATE :WS-STMT END-EXEC
           GOBACK.
