//NIGHTXFR JOB (ACCT),'SEND TO BUREAU',CLASS=A,MSGCLASS=X
//*
//* SEND THE NIGHTLY STATEMENT FILE TO THE PRINT BUREAU
//*
//SEND     EXEC PGM=FTP,
//             PARM='-r TLS BUREAU.EXAMPLE.COM (EXIT'
//NETRC    DD DSN=SEC.NIGHTXFR.NETRC,DISP=SHR
//OUTPUT   DD SYSOUT=*
//INPUT    DD *
BINARY
PUT 'STMT.NIGHTLY.PRINT' stmt.dat
QUIT
/*
