       IDENTIFICATION DIVISION.
       PROGRAM-ID. N2.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-LOCAL         PIC X(80).
       LINKAGE SECTION.
       01 LK-ARG           PIC X(80).
       PROCEDURE DIVISION USING LK-ARG.
           MOVE LK-ARG TO WS-LOCAL
           CALL 'SYSTEM' USING WS-LOCAL
           GOBACK.
