       IDENTIFICATION DIVISION.
       PROGRAM-ID. DBLOGIN.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01  WS-DB-USER      PIC X(8)  VALUE 'BATCH01'.
       01  WS-DB-PASSWORD  PIC X(12) VALUE 'Zq7r2Lm9Vx4p'.
       01  WS-RC           PIC S9(4) COMP.
       PROCEDURE DIVISION.
           CALL 'DBLOGON' USING WS-DB-USER WS-DB-PASSWORD WS-RC.
           GOBACK.
