       IDENTIFICATION DIVISION.
       PROGRAM-ID. ACCTRPT.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 GU-FUNC       PIC X(4) VALUE 'GU  '.
       01 GN-FUNC       PIC X(4) VALUE 'GN  '.
       01 ACCT-AREA     PIC X(37).
       LINKAGE SECTION.
       01 DB-PCB.
          05 PCB-DBD    PIC X(8).
          05 PCB-STATUS PIC XX.
          05 FILLER     PIC X(30).
       PROCEDURE DIVISION USING DB-PCB.
           CALL 'CBLTDLI' USING GU-FUNC DB-PCB ACCT-AREA.
           PERFORM UNTIL PCB-STATUS NOT = SPACES
               CALL 'CBLTDLI' USING GN-FUNC DB-PCB ACCT-AREA
           END-PERFORM.
           GOBACK.
