//ADMIN    JOB (ACCT),'USER ADMIN',CLASS=A
//STEP010  EXEC PGM=IKJEFT01
//SYSTSPRT DD SYSOUT=*
//SYSTSIN  DD *
  ADDUSER BATCHOP PASSWORD=SUMMER26 SPECIAL
  PERMIT PROD.PAYROLL ID(BATCHOP) ACCESS(ALTER)
/*
