//NIGHTLY  JOB (ACCT),'DB2 BATCH',CLASS=A,MSGCLASS=X
//STEP1    EXEC PGM=IKJEFT01
//SYSTSPRT DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//SYSTSIN  DD *
  DSN SYSTEM(DB2P)
  RUN PROGRAM(MAIN) PLAN(MAINPLAN)
  END
/*
//SYSIN    DD *
0012345678
/*
