       IDENTIFICATION DIVISION.
       PROGRAM-ID. PLAIN1.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01  WS-REC       PIC X(100).
       PROCEDURE DIVISION.
           MOVE SPACES TO WS-REC
           GOBACK.
