       IDENTIFICATION DIVISION.
       PROGRAM-ID. ACCTLST.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-NEXT PIC X(8).
       01 CA.
          05 CA-SELECTED PIC X(11).
       COPY ACCTS.
       PROCEDURE DIVISION.
           EXEC CICS RECEIVE MAP('ACCTA') MAPSET('ACCTS')
               INTO(ACCTAI) END-EXEC.
           MOVE ACCT1I TO CA-SELECTED.
           MOVE 'ACCTVIEW' TO WS-NEXT.
           EXEC CICS XCTL PROGRAM(WS-NEXT) COMMAREA(CA)
               END-EXEC.
           GOBACK.
