//TCUSTCPY JOB (ACCT),'REFRESH TEST DATA',CLASS=A,MSGCLASS=X
//*
//* REFRESH THE TEST CUSTOMER FILE
//*
//COPY     EXEC PGM=IDCAMS
//SYSPRINT DD SYSOUT=*
//IN       DD DSN=PROD.CUSTOMER.MASTER,DISP=SHR
//OUT      DD DSN=TEST.CUSTOMER.MASTER,DISP=OLD
//SYSIN    DD *
  REPRO INFILE(IN) OUTFILE(OUT) REUSE
/*
