//TCUSTCPY JOB (ACCT),'REFRESH TEST DATA',CLASS=A,MSGCLASS=X
//*
//* REFRESH THE TEST CATALOGUE FILE
//*
//COPY     EXEC PGM=IDCAMS
//SYSPRINT DD SYSOUT=*
//IN       DD DSN=PRODUCTS.CATALOG.MASTER,DISP=SHR
//OUT      DD DSN=TEST.CATALOG.MASTER,DISP=OLD
//SYSIN    DD *
  REPRO INFILE(IN) OUTFILE(OUT) REUSE
/*
