       IDENTIFICATION DIVISION.
       PROGRAM-ID. FREAD.
       ENVIRONMENT DIVISION.
       INPUT-OUTPUT SECTION.
       FILE-CONTROL.
           SELECT CONTROL-FILE ASSIGN TO 'control.dat'
               ORGANIZATION IS LINE SEQUENTIAL.
           SELECT WORK-FILE ASSIGN TO WS-NAME
               ORGANIZATION IS LINE SEQUENTIAL.
       DATA DIVISION.
       FILE SECTION.
       FD CONTROL-FILE.
       01 CONTROL-REC          PIC X(80).
       FD WORK-FILE.
       01 WORK-REC             PIC X(80).
       WORKING-STORAGE SECTION.
       01 WS-NAME              PIC X(80).
       PROCEDURE DIVISION.
           OPEN INPUT CONTROL-FILE
           READ CONTROL-FILE INTO WS-NAME
           OPEN INPUT WORK-FILE
           CLOSE CONTROL-FILE WORK-FILE
           GOBACK.
