// SPDX-License-Identifier: AGPL-3.0-or-later
// Enterprise COBOL's compiler options: every spelling each one answers to, and where it may be given.
//
// GENERATED - do not edit by hand. Run `node diag/generate-options.mjs` to rebuild it from
// provenance/enterprise-options.json, which names the IBM table and page behind each row.

// Each spelling's option, and whether the spelling turns the option off.
export const OPTION_SPELLINGS = {
  "APOST": ["APOST/QUOTE", false],
  "QUOTE": ["APOST/QUOTE", false],
  "Q": ["APOST/QUOTE", false],
  "ARITH": ["ARITH", false],
  "AR": ["ARITH", false],
  "CICS": ["CICS", false],
  "NOCICS": ["CICS", true],
  "CODEPAGE": ["CODEPAGE", false],
  "CP": ["CODEPAGE", false],
  "CURRENCY": ["CURRENCY", false],
  "NOCURRENCY": ["CURRENCY", true],
  "CURR": ["CURRENCY", false],
  "NOCURR": ["CURRENCY", true],
  "DBCS": ["DBCS", false],
  "NODBCS": ["DBCS", true],
  "NSYMBOL": ["NSYMBOL", false],
  "NS": ["NSYMBOL", false],
  "NUMBER": ["NUMBER", false],
  "NONUMBER": ["NUMBER", true],
  "NUM": ["NUMBER", false],
  "NONUM": ["NUMBER", true],
  "QUALIFY": ["QUALIFY", false],
  "QUA": ["QUALIFY", false],
  "SEQUENCE": ["SEQUENCE", false],
  "NOSEQUENCE": ["SEQUENCE", true],
  "SEQ": ["SEQUENCE", false],
  "NOSEQ": ["SEQUENCE", true],
  "SQL": ["SQL", false],
  "NOSQL": ["SQL", true],
  "SQLCCSID": ["SQLCCSID", false],
  "NOSQLCCSID": ["SQLCCSID", true],
  "SQLC": ["SQLCCSID", false],
  "NOSQLC": ["SQLCCSID", true],
  "SQLIMS": ["SQLIMS", false],
  "NOSQLIMS": ["SQLIMS", true],
  "SUPPRESS": ["SUPPRESS", false],
  "NOSUPPRESS": ["SUPPRESS", true],
  "SUPP": ["SUPPRESS", false],
  "NOSUPP": ["SUPPRESS", true],
  "WORD": ["WORD", false],
  "NOWORD": ["WORD", true],
  "WD": ["WORD", false],
  "NOWD": ["WORD", true],
  "XMLPARSE": ["XMLPARSE", false],
  "XP": ["XMLPARSE", false],
  "INTDATE": ["INTDATE", false],
  "CONDCOMP": ["CONDCOMP", false],
  "CC": ["CONDCOMP", false],
  "LANGUAGE": ["LANGUAGE", false],
  "LANG": ["LANGUAGE", false],
  "LINECOUNT": ["LINECOUNT", false],
  "LC": ["LINECOUNT", false],
  "LIST": ["LIST", false],
  "NOLIST": ["LIST", true],
  "MAP": ["MAP", false],
  "NOMAP": ["MAP", true],
  "OFFSET": ["OFFSET", false],
  "NOOFFSET": ["OFFSET", true],
  "OFF": ["OFFSET", false],
  "NOOFF": ["OFFSET", true],
  "SOURCE": ["SOURCE", false],
  "NOSOURCE": ["SOURCE", true],
  "S": ["SOURCE", false],
  "NOS": ["SOURCE", true],
  "SPACE": ["SPACE", false],
  "TERMINAL": ["TERMINAL", false],
  "NOTERMINAL": ["TERMINAL", true],
  "TERM": ["TERMINAL", false],
  "NOTERM": ["TERMINAL", true],
  "VBREF": ["VBREF", false],
  "NOVBREF": ["VBREF", true],
  "XREF": ["XREF", false],
  "NOXREF": ["XREF", true],
  "X": ["XREF", false],
  "NOX": ["XREF", true],
  "COMPILE": ["COMPILE", false],
  "NOCOMPILE": ["COMPILE", true],
  "C": ["COMPILE", false],
  "NOC": ["COMPILE", true],
  "COPYRIGHT": ["COPYRIGHT", false],
  "NOCOPYRIGHT": ["COPYRIGHT", true],
  "CPYR": ["COPYRIGHT", false],
  "NOCPYR": ["COPYRIGHT", true],
  "DECK": ["DECK", false],
  "NODECK": ["DECK", true],
  "D": ["DECK", false],
  "NOD": ["DECK", true],
  "NAME": ["NAME", false],
  "NONAME": ["NAME", true],
  "OBJECT": ["OBJECT", false],
  "NOOBJECT": ["OBJECT", true],
  "OBJ": ["OBJECT", false],
  "NOOBJ": ["OBJECT", true],
  "PGMNAME": ["PGMNAME", false],
  "PGMN": ["PGMNAME", false],
  "SERVICE": ["SERVICE", false],
  "NOSERVICE": ["SERVICE", true],
  "SERV": ["SERVICE", false],
  "NOSERV": ["SERVICE", true],
  "ADV": ["ADV", false],
  "NOADV": ["ADV", true],
  "AFP": ["AFP", false],
  "ARCH": ["ARCH", false],
  "AWO": ["AWO", false],
  "NOAWO": ["AWO", true],
  "BLOCK0": ["BLOCK0", false],
  "NOBLOCK0": ["BLOCK0", true],
  "DEFINE": ["DEFINE", false],
  "NODEFINE": ["DEFINE", true],
  "DEF": ["DEFINE", false],
  "NODEF": ["DEFINE", true],
  "DISPSIGN": ["DISPSIGN", false],
  "DS": ["DISPSIGN", false],
  "DLL": ["DLL", false],
  "NODLL": ["DLL", true],
  "EXPORTALL": ["EXPORTALL", false],
  "NOEXPORTALL": ["EXPORTALL", true],
  "EXP": ["EXPORTALL", false],
  "NOEXP": ["EXPORTALL", true],
  "FASTSRT": ["FASTSRT", false],
  "NOFASTSRT": ["FASTSRT", true],
  "FSRT": ["FASTSRT", false],
  "NOFSRT": ["FASTSRT", true],
  "HGPR": ["HGPR", false],
  "INITIAL": ["INITIAL", false],
  "NOINITIAL": ["INITIAL", true],
  "INLINE": ["INLINE", false],
  "NOINLINE": ["INLINE", true],
  "INL": ["INLINE", false],
  "NOINL": ["INLINE", true],
  "INVDATA": ["INVDATA", false],
  "NOINVDATA": ["INVDATA", true],
  "NOINV": ["INVDATA", true],
  "INVD": ["INVDATA", false],
  "NOINVD": ["INVDATA", true],
  "JAVAIOP": ["JAVAIOP", false],
  "NOJAVAIOP": ["JAVAIOP", true],
  "JIOP": ["JAVAIOP", false],
  "NOJIOP": ["JAVAIOP", true],
  "LP": ["LP", false],
  "MAXPCF": ["MAXPCF", false],
  "NUMCHECK": ["NUMCHECK", false],
  "NONUMCHECK": ["NUMCHECK", true],
  "NC": ["NUMCHECK", false],
  "NONC": ["NUMCHECK", true],
  "NUMPROC": ["NUMPROC", false],
  "OPTIMIZE": ["OPTIMIZE", false],
  "NOOPTIMIZE": ["OPTIMIZE", true],
  "OPT": ["OPTIMIZE", false],
  "OUTDD": ["OUTDD", false],
  "OUT": ["OUTDD", false],
  "PARMCHECK": ["PARMCHECK", false],
  "NOPARMCHECK": ["PARMCHECK", true],
  "PC": ["PARMCHECK", false],
  "NOPC": ["PARMCHECK", true],
  "TRUNC": ["TRUNC", false],
  "TUNE": ["TUNE", false],
  "VLR": ["VLR", false],
  "ZONECHECK": ["ZONECHECK", false],
  "NOZONECHECK": ["ZONECHECK", true],
  "NOZC": ["ZONECHECK", true],
  "ZC": ["ZONECHECK", false],
  "ZONEDATA": ["ZONEDATA", false],
  "ZD": ["ZONEDATA", false],
  "ZWB": ["ZWB", false],
  "NOZWB": ["ZWB", true],
  "BUFSIZE": ["BUFSIZE", false],
  "BUF": ["BUFSIZE", false],
  "DATA": ["DATA", false],
  "DYNAM": ["DYNAM", false],
  "NODYNAM": ["DYNAM", true],
  "DYN": ["DYNAM", false],
  "NODYN": ["DYNAM", true],
  "RENT": ["RENT", false],
  "NORENT": ["RENT", true],
  "RMODE": ["RMODE", false],
  "STGOPT": ["STGOPT", false],
  "NOSTGOPT": ["STGOPT", true],
  "SO": ["STGOPT", false],
  "NOSO": ["STGOPT", true],
  "DIAGTRUNC": ["DIAGTRUNC", false],
  "NODIAGTRUNC": ["DIAGTRUNC", true],
  "DTR": ["DIAGTRUNC", false],
  "NODTR": ["DIAGTRUNC", true],
  "DUMP": ["DUMP", false],
  "NODUMP": ["DUMP", true],
  "DU": ["DUMP", false],
  "NODU": ["DUMP", true],
  "FLAG": ["FLAG", false],
  "NOFLAG": ["FLAG", true],
  "F": ["FLAG", false],
  "NOF": ["FLAG", true],
  "FLAGSTD": ["FLAGSTD", false],
  "NOFLAGSTD": ["FLAGSTD", true],
  "INITCHECK": ["INITCHECK", false],
  "NOINITCHECK": ["INITCHECK", true],
  "IC": ["INITCHECK", false],
  "NOIC": ["INITCHECK", true],
  "RULES": ["RULES", false],
  "NORULES": ["RULES", true],
  "SSRANGE": ["SSRANGE", false],
  "NOSSRANGE": ["SSRANGE", true],
  "SSR": ["SSRANGE", false],
  "NOSSR": ["SSRANGE", true],
  "TEST": ["TEST", false],
  "NOTEST": ["TEST", true],
  "ADATA": ["ADATA", false],
  "NOADATA": ["ADATA", true],
  "COPYLOC": ["COPYLOC", false],
  "NOCOPYLOC": ["COPYLOC", true],
  "CPLC": ["COPYLOC", false],
  "NOCPLC": ["COPYLOC", true],
  "EXIT": ["EXIT", false],
  "NOEXIT": ["EXIT", true],
  "NOEX": ["EXIT", true],
  "EX": ["EXIT", false],
  "MDECK": ["MDECK", false],
  "NOMDECK": ["MDECK", true],
  "NOMD": ["MDECK", true],
  "MD": ["MDECK", false],
  "OPTFILE": ["OPTFILE", false],
  "SMARTBIN": ["SMARTBIN", false],
  "NOSMARTBIN": ["SMARTBIN", true],
  "THREAD": ["THREAD", false],
  "NOTHREAD": ["THREAD", true],
  "VSAMOPENFS": ["VSAMOPENFS", false],
  "VS": ["VSAMOPENFS", false],
};

// The options with a rule on where they may be given: not in a CBL or PROCESS statement (process),
// in one only before a batch compilation's first program (firstProgramOnly), or not as an
// installation default (installationDefault). Every other option may be given anywhere.
export const OPTION_PLACEMENT = {
  "CICS": { firstProgramOnly: true },
  "SQL": { firstProgramOnly: true },
  "SQLIMS": { firstProgramOnly: true },
  "DEFINE": { firstProgramOnly: true },
  "JAVAIOP": { firstProgramOnly: true },
  "LP": { firstProgramOnly: true },
  "OUTDD": { firstProgramOnly: true },
  "BUFSIZE": { firstProgramOnly: true },
  "ADATA": { process: false },
  "COPYLOC": { firstProgramOnly: true },
  "EXIT": { process: false },
  "MDECK": { process: false },
  "OPTFILE": { installationDefault: false },
};
