// SPDX-License-Identifier: AGPL-3.0-or-later
// The words the reference pages need and the code cannot carry: what each command and option does,
// the statuses each command exits with, and the environment variables cobolwork reads. They reach
// the reader through `cobolwork capabilities`; tests hold them to the command line and to the code.
import { EXIT } from './exit.mjs';

export const EXIT_MEANING = {
  [EXIT.pass]: 'It ran. A command that gives a verdict answered yes.',
  [EXIT.fail]: 'It ran, and the verdict is no.',
  [EXIT.couldNotRun]: 'It could not run: a usage error, or an input it cannot use. Nothing was judged.',
  [EXIT.undecided]: 'Undecided: it ran, and what it could not read leaves no verdict.',
  [EXIT.compilerFailed]: 'The compiler refused a program after the checks passed.',
};

const DONE = [{ status: EXIT.pass, meaning: 'The command ran.' }, { status: EXIT.couldNotRun, meaning: 'A usage error, or the command could not run.' }];
const VERDICT = (pass) => [
  { status: EXIT.pass, meaning: pass },
  { status: EXIT.fail, meaning: 'Fail.' },
  { status: EXIT.undecided, meaning: 'Undecided.' },
  { status: EXIT.couldNotRun, meaning: 'The command could not run.' },
];

export const COMMAND_FACTS = {
  scan: { summary: 'Run every rule set over a tree and write the findings.', exit: DONE },
  flow: { summary: 'Write the data-flow findings with the path the data took.', exit: DONE },
  inventory: { summary: 'List what is in a tree and what could not be read.', exit: DONE },
  parse: { summary: 'Parse one source file and write a summary of its structure.', exit: DONE },
  sbom: { summary: 'Write a CycloneDX 1.6 bill of materials for the tree.', exit: DONE },
  diff: { summary: 'Write what a change reaches: moved layouts, new call targets, and findings added or removed.', exit: DONE },
  baseline: { summary: 'Accept what a scan reports now until a date, in the tree\'s baseline file.', exit: DONE },
  tui: { summary: 'Read a scan in the terminal, coverage first.', exit: DONE },
  explain: { summary: 'Write one finding with the source of every hop and the declaration of every item on its path.', exit: DONE },
  advise: { summary: 'Write every remediation and best practice for the repository as one document.', exit: DONE },
  gate: { summary: 'Judge whether a patch fixed one finding and moved nothing else.', exit: [{ status: EXIT.pass, meaning: 'The command ran. With --exit-code: the patch passed.' }, { status: EXIT.fail, meaning: 'With --exit-code: the patch failed.' }, { status: EXIT.undecided, meaning: 'With --exit-code: undecided.' }, DONE[1]] },
  build: { summary: 'The build gate: rank every finding, check the policy, and run the compiler only on a pass.', exit: [...VERDICT('Pass.'), { status: EXIT.compilerFailed, meaning: 'The compiler failed after a pass.' }] },
  evidence: { summary: 'Verify, seal, anchor or sign the evidence a run records.', exit: [{ status: EXIT.pass, meaning: 'seal, anchor and sign: done. verify: verified and sealed.' }, { status: EXIT.fail, meaning: 'verify: broken, contradicted or not sealed.' }, { status: EXIT.undecided, meaning: 'verify: undetermined.' }, DONE[1]] },
  capabilities: { summary: 'Write what this cobolwork can do as one document.', exit: DONE },
};

const O = (value, summary, commands) => ({ value, summary, ...(commands && { commands }) });
export const OPTION_FACTS = {
  '--help': O(null, 'Print the usage text and exit.'),
  '--version': O(null, 'Print the version and exit.'),
  '--rules-path': O('gitleaks', 'Print the path of the mainframe credential rules and exit.'),
  '--json': O(null, 'Write the document as JSON. It is the only form.'),
  '--format': O('json|sarif|md', 'Output format. The default is json. md is for advise.'),
  '--out': O('file', 'Write to a file instead of standard output.'),
  '--repos': O(null, 'Treat each immediate subdirectory as its own repository.'),
  '--only': O('sets', 'A comma-separated subset of the rule sets.'),
  '--quiet': O(null, 'Write the summary only.'),
  '--full-trace': O(null, 'List every hop of a data-flow path, not its two ends.'),
  '--all-routes': O(null, 'Give each data-flow finding every statement on any route from its sources.'),
  '--baseline': O('file', 'The judgements to apply. Without it, the tree\'s own baseline file.'),
  '--no-baseline': O(null, 'Apply no baseline, the tree\'s own included.'),
  '--advisories': O('file[,file]', 'A customer\'s own advisory extract (JSON), loaded for this run only.'),
  '--copylib': O('dir[,dir]', 'Copy libraries kept outside the repository, searched after the tree\'s own copybooks.'),
  '--pds-export': O(null, 'The directory holds partitioned data sets\' members as files; findings name DATA.SET/MEMBER.'),
  '--mvs38-forms': O(null, 'Read the operands MVS 3.8\'s system macros take. This is the default.'),
  '--no-mvs38-forms': O(null, 'Refuse the operands MVS 3.8\'s system macros take and z/OS 3.1 does not list.'),
  '--hlasm-optable': O('table', 'Read assembler source with this HLASM operation code table.'),
  '--evidence': O('dir', 'Record this run in a hash-chained journal and ledger in this directory, or in COBOLWORK_EVIDENCE.'),
  '--name': O('name', 'sbom: the name of the estate. The default is the directory\'s name.'),
  '--base': O('ref', 'The git revision to compare against.'),
  '--head': O('ref', 'The revision under review. The default is the working tree.'),
  '--reason': O('text', 'baseline: why the findings are accepted.'),
  '--who': O('name', 'baseline: who accepts them.'),
  '--expires': O('date', 'baseline: the date the acceptance ends.'),
  '--action': O('accept|false-positive|wont-fix', 'baseline: the judgement each new entry records.'),
  '--rule': O('ids', 'baseline: the rules the entry covers.'),
  '--report': O('file', 'Read a stored scan report instead of scanning.'),
  '--keys': O('ispf|modern', 'tui: F3 and a command line, or Esc and letters. The default is ispf.'),
  '--ironwork': O('path', 'Check programs with this ironwork.', {
    build: 'After a pass, run ironwork check on every program. A program ironwork rejects exits 4; one it does not model yet leaves the build undecided.',
    gate: 'Check the patch with ironwork check.',
    advise: 'Compile every program with ironwork and read its messages.',
  }),
  '--target': O('fingerprint', 'gate: the finding the patch is meant to fix, as the base reports it.'),
  '--cobc': O('path', 'gate: check the patch with this cobc -fsyntax-only rather than ironwork.'),
  '--exit-code': O(null, 'gate: exit with the verdict rather than 0 whenever it ran.'),
  '--target-only': O(null, 'gate: judge only the target and coverage, for a revision others have changed since.'),
  '--policy': O('file', 'build: an organisation\'s floor policy. The repository\'s policy can tighten it and never loosen it.'),
  '--provenance': O('file', 'build: write what was scanned, under which policy, and what was compiled.'),
  '--provenance-format': O('cobolwork|slsa', 'build: the record as cobolwork writes it, or an in-toto statement with the SLSA Provenance v1 predicate.'),
  '--artifact': O('path[,path]', 'build: what the compiler produced, named as subjects of the SLSA statement.'),
  '--equivalence': O('file[,file]', 'build: ironwork equivalence statements for the programs the change edits.'),
  '--allowed-signers': O('file', 'An OpenSSH allowed_signers file for namespace cobolwork-evidence. build refuses one inside the repository.'),
  '--precompile': O(null, 'build: translate each program that holds EXEC SQL or EXEC CICS and run the compiler on it with -fsyntax-only.'),
  '--ssh-key': O('file', 'evidence seal: sign with this SSH key.'),
  '--signer': O('program', 'evidence seal: sign with this program.'),
  '--expect-key': O('keyid', 'evidence: the key id a seal must carry.'),
  '--anchor-git': O('repo', 'evidence: the git repository that witnesses a seal.'),
  '--ref': O('ref', 'evidence: the ref that counts. The default is @{upstream}.'),
  '--anchor-pin': O('commit', 'evidence verify: the witness commit an earlier verify reported.'),
  '--push': O(null, 'evidence anchor: push the witness.'),
  '--max-unsealed': O('n', 'evidence verify: how many ledger records may follow the newest seal.'),
  '--tsq': O('file', 'evidence anchor: write an RFC 3161 request.'),
  '--tsr': O('file', 'evidence verify: read an RFC 3161 response.'),
  '--tsa-ca': O('file', 'evidence verify: the authority\'s CA certificate.'),
  '--cosign-bundle': O('file', 'evidence verify: a transparency-log bundle over a seal, checked by cosign.'),
  '--cosign-key': O('file', 'evidence verify: the cosign public key.'),
  '--certificate-identity': O('id', 'evidence verify: the certificate identity cosign expects.'),
  '--certificate-oidc-issuer': O('url', 'evidence verify: the OIDC issuer cosign expects.'),
  '--trusted-root': O('file', 'evidence verify: the trusted root cosign uses.'),
  '--insecure-ignore-tlog': O(null, 'evidence verify: do not require the transparency log entry.'),
};

const E = (name, value, summary) => ({ name, value, summary });
export const ENVIRONMENT = [
  E('COBOLWORK_ABENDS', 'path list', 'Fuzz runs from ironwork\'s harness. Each abend an input caused becomes a finding. Refused from inside the scanned tree.'),
  E('COBOLWORK_ADVISORIES', 'path list', 'Advisory extracts loaded for the run, as --advisories.'),
  E('COBOLWORK_BUILDER_ID', 'text', 'build --provenance-format slsa: the builder id the statement records.'),
  E('COBOLWORK_CONTROL_WORKERS', 'integer', 'How many worker threads analyse programs. The default is one fewer than the machine\'s threads, at most four.'),
  E('COBOLWORK_COPYPATH', 'path list', 'Copy libraries searched after the tree\'s own copybooks. Read before COBCPY.'),
  E('COBOLWORK_EVIDENCE', 'directory', 'The evidence directory, as --evidence.'),
  E('COBOLWORK_EXECUTION', 'path list', 'Reports ironwork run --coverage wrote from runs of the estate\'s programs. Refused from inside the scanned tree.'),
  E('COBOLWORK_FREE_MEMORY_MB', 'megabytes', 'The free memory a scan may count on, for a container or shared runner whose share is not what the machine reports.'),
  E('COBOLWORK_MAX_SOURCE_BYTES', 'bytes', 'A budget for source read. Files past it are counted as unread.'),
  E('COBOLWORK_PLI', '0', 'Set to 0 and a scan does not read PL/I.'),
  E('COBOLWORK_REACH', 'path list', 'A reduced RACF unload or reachability extract. It overrides the site file\'s open, restricted and privileged keys. Refused from inside the scanned tree.'),
  E('COBOLWORK_VERIFY_REUSE', '1', 'Set to 1 and a scan checks each reused analysis against a fresh one.'),
  E('COBOLWORK_WITNESS', 'path list', 'Results of tests run against findings, keyed by fingerprint. Refused from inside the scanned tree.'),
  E('COBCPY', 'path list', 'Copy libraries searched after COBOLWORK_COPYPATH, as GnuCOBOL reads it.'),
  E('NO_COLOR', 'any value', 'tui: use no colour.'),
  E('SOURCE_DATE_EPOCH', 'seconds', 'sbom and build provenance: the time to record, so the document is the same on every run.'),
];
