//PAYXFER  JOB (ACCT),'PAYROLL FROM PARTNER',CLASS=A,MSGCLASS=X
//*
//* FETCH THE PAYMENTS PARTNER'S RETURN FILE
//*
//XFER     EXEC PGM=FTP,
//             PARM='-r TLS PARTNER.EXAMPLE.COM 21 (EXIT'
//NETRC    DD DSN=SEC.PAYXFER.NETRC,DISP=SHR
//OUTPUT   DD SYSOUT=*
//INPUT    DD *
BINARY
GET payroll.ret 'PROD.PAYROLL.RETURNS'
QUIT
/*
