       IDENTIFICATION DIVISION.
       PROGRAM-ID. OPAQUE1.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01  WS-PTR       USAGE IS POINTER.
       LINKAGE SECTION.
       01  LK-REC       PIC X(100).
       PROCEDURE DIVISION.
           SET ADDRESS OF LK-REC TO WS-PTR
           GOBACK.
