       IDENTIFICATION DIVISION.
       PROGRAM-ID. GREET.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-IN              PIC X(40).
       01 WS-LEN             PIC S9(4) COMP VALUE 40.
       01 WS-MSG             PIC X(20).
       PROCEDURE DIVISION.
           EXEC CICS RECEIVE INTO(WS-IN) LENGTH(WS-LEN) END-EXEC
           STRING WS-IN DELIMITED BY SPACE INTO WS-MSG
           END-STRING
           EXEC CICS SEND TEXT FROM(WS-MSG) LENGTH(20) END-EXEC
           EXEC CICS RETURN END-EXEC.
