       IDENTIFICATION DIVISION.
       PROGRAM-ID. X2.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-BAL           PIC X(16).
       01 WS-BUF           PIC X(64).
       PROCEDURE DIVISION.
           EXEC SQL SELECT BALANCE INTO :WS-BAL FROM ACCTS
                WHERE ACCT = 1 END-EXEC
           MOVE WS-BAL TO WS-BUF
           EXEC CICS WEB SEND FROM(WS-BUF) FROMLENGTH(64) END-EXEC
           GOBACK.
