       IDENTIFICATION DIVISION.
       PROGRAM-ID. MSGLOG.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-QUEUE PIC X(4) VALUE 'CSMT'.
       01 WS-RECV.
          05 WS-RECV-TRAN PIC X(4).
          05 WS-RECV-DATA PIC X(76).
       01 WS-LEN PIC S9(4) COMP.
       01 WRITE-MSG.
          05 WRITE-MSG-TIME PIC X(8).
          05 WRITE-MSG-TEXT PIC X(76).
       PROCEDURE DIVISION.
           MOVE 80 TO WS-LEN.
           EXEC CICS RECEIVE INTO(WS-RECV) LENGTH(WS-LEN)
               END-EXEC.
           IF WS-RECV-DATA IS NOT ALPHABETIC
               EXEC CICS RETURN END-EXEC
           END-IF.
           MOVE WS-RECV-DATA TO WRITE-MSG-TEXT.
           EXEC CICS WRITEQ TD QUEUE(WS-QUEUE) FROM(WRITE-MSG)
               END-EXEC.
           EXEC CICS RETURN END-EXEC.
