       IDENTIFICATION DIVISION.
       PROGRAM-ID. C1.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-BUF           PIC X(100).
       PROCEDURE DIVISION.
           EXEC CICS RECEIVE INTO(WS-BUF) LENGTH(100) END-EXEC
           EXEC CICS LINK PROGRAM('C2') COMMAREA(WS-BUF) END-EXEC
           EXEC CICS RETURN END-EXEC.
