//FTPSEND  JOB 'FTP JCL',CLASS=A,MSGCLASS=H
//*
//* SEND THE DAILY EXTRACT TO THE REPORTING SERVER
//*
//STEP1    EXEC PGM=FTP,REGION=2048K
//SYSIN    DD *
 10.20.30.40
 rptuser
 rptpass1
 ASCII
 cd /inbound
 PUT 'PAY.EXTRACT.DAILY' daily.txt
 QUIT
/*
