       IDENTIFICATION DIVISION.
       PROGRAM-ID. CUSTCUR.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
           EXEC SQL INCLUDE SQLCA END-EXEC.
       01 WS-NAME            PIC X(30).
           EXEC SQL DECLARE C1 CURSOR FOR
               SELECT NAME FROM CUST END-EXEC.
       PROCEDURE DIVISION.
           EXEC SQL OPEN C1 END-EXEC
           EXEC SQL FETCH C1 INTO :WS-NAME END-EXEC
           DISPLAY WS-NAME
           EXEC SQL CLOSE C1 END-EXEC
           GOBACK.
