       IDENTIFICATION DIVISION.
       PROGRAM-ID. SEGCMD.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 DLI-FUNC      PIC X(4) VALUE 'GU  '.
       01 SEG-AREA.
          05 SEG-COMMAND PIC X(72).
          05 FILLER      PIC X(8).
       LINKAGE SECTION.
       01 DB-PCB        PIC X(40).
       PROCEDURE DIVISION USING DB-PCB.
           CALL 'CBLTDLI' USING DLI-FUNC DB-PCB SEG-AREA.
           CALL 'SYSTEM' USING SEG-COMMAND.
           GOBACK.
