       IDENTIFICATION DIVISION.
       PROGRAM-ID. CNOEIB.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-NUM           PIC X(10).
       LINKAGE SECTION.
       01 DFHCOMMAREA.
          05 CA-CUSTOMER   PIC X(10).
          05 CA-REST       PIC X(90).
       PROCEDURE DIVISION.
           MOVE CA-CUSTOMER TO WS-NUM
           EXEC CICS RETURN END-EXEC.
