       IDENTIFICATION DIVISION.
       PROGRAM-ID. CUSTINQ.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-RESP            PIC S9(8) COMP.
       01 WS-KEY             PIC X(8).
       01 WS-REC             PIC X(80).
       PROCEDURE DIVISION.
           MOVE 'C0000001' TO WS-KEY
           EXEC CICS READ FILE('CUSTFIL') INTO(WS-REC)
               RIDFLD(WS-KEY) RESP(WS-RESP) END-EXEC
           IF WS-RESP NOT = DFHRESP(NORMAL)
               EXEC CICS RETURN END-EXEC
           END-IF
           EXEC CICS SEND TEXT FROM(WS-REC) LENGTH(80) END-EXEC
           EXEC CICS RETURN END-EXEC.
