//TPAYCLN  JOB (ACCT),'PAYROLL CLEAR-DOWN',CLASS=A,MSGCLASS=X
//*
//* CLEAR DOWN BEFORE THE RUN
//*
//CLEANUP  EXEC PGM=IEFBR14
//EXTRACT  DD DSN=TEST.PAYROLL.EXTRACT,DISP=(MOD,DELETE),
//            SPACE=(TRK,(1,1)),UNIT=SYSDA
//MASTER   DD DSN=PROD.PAYROLL.MASTER,DISP=(OLD,DELETE)
